resources:
  containers:
  - container: hugo
    image: 'barrydobson/hugo:ci'

pool: 'Hosted Ubuntu 1604'
container: hugo

steps:
- script: |
    cd /pwd/barrydobsonß
    make build
  displayName: 'Hugo generate barrydobson'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    publishLocation: FilePath
    targetPath: $(Build.ArtifactStagingDirectory)
    pathtoPublish: '$(Build.SourcesDirectory)/public'
    artifactName: drop