pool:
  vmImage: Hosted VS2017
steps:
- task: giuliovdev.hugo-extension.hugo-build-task.HugoTask@1
  displayName: 'Hugo generate barrydobson'
  inputs:
    source: barrydobson
    destination: '$(Build.ArtifactStagingDirectory)'
    baseURL: 'https://www.barrydobson.com'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
