baseURL = "https://www.barrydobson.com/"
languageCode = "en-gb"
title = "Barry Dobson"
theme = "hugo-dusk"
paginate = 5
googleAnalytics = "UA-118951548-2"
enableGitInfo = true
disqusShortname = "barrydobsonsblog"
enableRobotsTXT = true

# use Chroma for syntax highlight
pygmentsStyle = "monokai" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[params]
  contentTypeName = "post"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  showMenuItems = 0
  fullWidthTheme = false
  centerTheme = true  
  socialShare = true
  delayDisqus = true
  github = "barrydobson"
  twitter = "barrydobson"
  linkedin = "barry-dobson-aa8614113"

[Author]
  name = "Barry Dobson"
  website = "www.barrydobson.com"
  github = "barrydobson"
  twitter = "barrydobson"
  linkedin = "barry-dobson-aa8614113"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
  
[languages]
  [languages.en]
    title = "Barry Dobson"
    subtitle = "A blog about software development and devops"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Barry Dobson"
      logoHomeLink = "/"